//
// Created by XI on 2022/11/29.
//

#ifndef POINTCLOUDREGISTRATION_SRC_ALGORITHM_ALGORITHM_GLOBAL_H_
#define POINTCLOUDREGISTRATION_SRC_ALGORITHM_ALGORITHM_GLOBAL_H_

#define ALGORITHM_EXPORT __declspec(dllexport)

#endif // POINTCLOUDREGISTRATION_SRC_ALGORITHM_ALGORITHM_GLOBAL_H_
