//
// Created by XI on 2023/9/30.
//

#ifndef POINTCLOUDREGISTRATION_SRC_UTILITIES_UTILITIESHLOBAL_H_
#define POINTCLOUDREGISTRATION_SRC_UTILITIES_UTILITIESHLOBAL_H_

#include <QtGlobal>

//#ifndef BUILD_STATIC
//#if defined(UTILITIES_LIB)
#define UTILITIES_EXPORT Q_DECL_EXPORT
//#else
//#define UTILITIES_EXPORT Q_DECL_IMPORT
//#endif
//#else
//#define UTILITIES_EXPORT
//#endif

#endif // POINTCLOUDREGISTRATION_SRC_UTILITIES_UTILITIESHLOBAL_H_
