//
// Created by XI on 2022/12/1.
//

#ifndef POINTCLOUDREGISTRATION_SRC_REGISTRATION_REGISTRATION_GLOBAL_H_
#define POINTCLOUDREGISTRATION_SRC_REGISTRATION_REGISTRATION_GLOBAL_H_

#include <QtGlobal>

//#ifndef BUILD_STATIC
//#if defined(REGISTRATION_LIB)
#define REGISTRATION_EXPORT Q_DECL_EXPORT
//#else
//#define REGISTRATION_EXPORT Q_DECL_IMPORT
//#endif
//#else
//#define REGISTRATION_EXPORT
//#endif
#endif // POINTCLOUDREGISTRATION_SRC_REGISTRATION_REGISTRATION_GLOBAL_H_
