//
// Created by XI on 2022/12/1.
//

#ifndef POINTCLOUDREGISTRATION_SRC_REGISTRATION_REGISTRATION_GLOBAL_H_
#define POINTCLOUDREGISTRATION_SRC_REGISTRATION_REGISTRATION_GLOBAL_H_


#define REGISTRATION_EXPORT __declspec(dllexport)

#endif // POINTCLOUDREGISTRATION_SRC_REGISTRATION_REGISTRATION_GLOBAL_H_
