//
// Created by XI on 2023/2/24.
//

#ifndef POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_PROBLEMS_PROBLEMS_H_
#define POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_PROBLEMS_PROBLEMS_H_

#include "MultimodalBenchmarkFunctions/MBFs.h"
#include "UnimodalBenchmarkFunctions/UBFs.h"
#include "Fixed-dimenstionMultimodalBenchmarkFunctions/FMBFs.h"

#endif // POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_PROBLEMS_PROBLEMS_H_
