//
// Created by XI on 2022/11/29.
//

#ifndef POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_OPTIMIZATIONALGORITHMSGLOBAL_H_
#define POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_OPTIMIZATIONALGORITHMSGLOBAL_H_

#include <QtGlobal>

//#ifndef BUILD_STATIC
//#if defined(ALGORITHM_LIB)
#define ALGORITHM_EXPORT Q_DECL_EXPORT
//#else
//#define ALGORITHM_EXPORT Q_DECL_IMPORT
//#endif
//#else
//#define ALGORITHM_EXPORT
//#endif

#endif // POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_OPTIMIZATIONALGORITHMSGLOBAL_H_
