//
// Created by XI on 2022/11/29.
//

#ifndef POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_OPTIMIZATIONALGORITHMSGLOBAL_H_
#define POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_OPTIMIZATIONALGORITHMSGLOBAL_H_

#define ALGORITHM_EXPORT __declspec(dllexport)

#endif // POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_OPTIMIZATIONALGORITHMSGLOBAL_H_
