//
// Created by XI on 2023/6/1.
//

#ifndef POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_ALGORITHM_SINGERINITMCTLBO_H_
#define POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_ALGORITHM_SINGERINITMCTLBO_H_

class SingerInitMCTLBO
{};

#endif // POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_ALGORITHM_SINGERINITMCTLBO_H_
