//
// Created by XI on 2023/2/24.
//

#ifndef POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_PROBLEMS_FIXED_DIMENSTIONMULTIMODALBENCHMARKFUNCTIONS_FMBFS_H_
#define POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_PROBLEMS_FIXED_DIMENSTIONMULTIMODALBENCHMARKFUNCTIONS_FMBFS_H_

#include "FMBF1.h"
#include "FMBF10.h"
#include "FMBF2.h"
#include "FMBF3.h"
#include "FMBF4.h"
#include "FMBF5.h"
#include "FMBF6.h"
#include "FMBF7.h"
#include "FMBF8.h"
#include "FMBF9.h"

#endif // POINTCLOUDREGISTRATION_SRC_OPTIMIZATIONALGORITHMS_PROBLEMS_FIXED_DIMENSTIONMULTIMODALBENCHMARKFUNCTIONS_FMBFS_H_
